### ISSUE TITLE
2/28 Weekly Update

### ISSUE THREAD

**Issue by prb55** [taishanahan/Pres-Inaug-Project#6]
1) Uploaded our website to the server (http://inaug-themes.obdurodon.org/)
2) Talked about who did what for the midterm assignment
3) Established our markup freeze date (3/21)
4) Decided our exchange process to verify each others markup
-- Preetam will look over Tai's speeches
-- Tai will look over Jack's speeches
-- Jack will look over Preetam's speeches

## Todos:
- [ ] Finish marking up last few speeches
- [ ] Start verifying each others markup
- [ ] Continue developing the website
